---
# NOTE: This playbook  assumes, asdf is set in dotfiles
- name: Install essential packages for asdf to work
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ asdf_essential_package }}"
  tags:
    - asdf
    - ubuntu
