---
- name: Install build dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ alacritty_dependencies }}"
  become: true

- name: Clone the alacritty repository
  git:
    repo: "{{ alacritty_git_repo }}"
    version: "{{ alacritty_git_version }}"
    dest: "{{ alacritty_temp_dest }}"

- name: Find the path to zsh
  command: which zsh
  register: zsh_path
  changed_when: false

- name: Add asdf rust plugin
  shell: $ASDF_DATA_DIR/bin/asdf plugin add rust
  args:
    executable: "{{ zsh_path.stdout }}"
  become: true
  become_user: "{{ user }}"
  changed_when: false

- name: Install stable Rust
  shell: $ASDF_DATA_DIR/bin/asdf install rust stable
  args:
    executable: "{{ zsh_path.stdout }}"
  become: true
  become_user: "{{ user }}"
  changed_when: false

- name: Set local enviroment
  shell: $ASDF_DATA_DIR/bin/asdf local rust stable
  args:
    chdir: /tmp/alacritty
    executable: "{{ zsh_path.stdout }}"
  become: true
  become_user: "{{ user }}"
  changed_when: false

- name: Build alacritty
  shell: $ASDF_DATA_DIR/shims/cargo build --release
  args:
    chdir: /tmp/alacritty
    executable: "{{ zsh_path.stdout }}"
  changed_when: false

- name: Install alacritty
  shell: |
    cp target/release/alacritty /usr/local/bin
    cp target/release/alacritty /usr/local/bin
    cp extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg
    desktop-file-install extra/linux/Alacritty.desktop
    update-desktop-database
  args:
    chdir: /tmp/alacritty
  become: true
  changed_when: false
