---
alacritty_dependencies:
  - cmake
  - pkg-config
  - libfreetype6-dev
  - libfontconfig1-dev
  - libxcb-xfixes0-dev
  - libxkbcommon-dev
  - desktop-file-utils

alacritty_git_repo: https://github.com/alacritty/alacritty.git

alacritty_git_version: master

alacritty_temp_dest: /tmp/alacritty
