---
- name: Setup workstation
  hosts: localhost
  become: true
  vars:
    user: "{{ lookup('env', 'USER') }}"
  roles:
    - role: zsh
    - role: neovim
    - role: ssh
    - role: asdf
    - role: alacritty
