---
- name: Clone vim git repository
  git:
    repo: "{{ neovim_git_repo }}"
    dest: "{{ neovim_temp_dir }}"
    version: "{{ neovim_version }}"
  tags:
    - vim
    - docker-env
    - ubuntu

- name: Set permissions to directory {{ neovim_temp_dir }}
  become: true
  file:
    path: "{{ neovim_temp_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0755"
  tags:
    - vim
    - docker-env
    - ubuntu

- name: Install pre requirements
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ neovim_prerequisite_packages }}"
  become: true
  tags:
    - vim
    - docker-env
    - ubuntu

- name: Install lazygit
  shell: |
    set -o pipefail
    LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep -Po '"tag_name": "v\K[^"]*')
    curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
    tar xf lazygit.tar.gz lazygit
    sudo install lazygit /usr/local/bin
  args:
    executable: /bin/bash
  become: true
  changed_when: false
  tags:
    - vim
    - docker-env
    - ubuntu

- name: Run make command and build vim
  shell: |
    make CMAKE_BUILD_TYPE=RelWithDebInfo
    make install
  args:
    chdir: "{{ neovim_temp_dir }}"
  become: true
  changed_when: false
  tags:
    - vim
    - docker-env
    - ubuntu
